### ISSUE TITLE
worker process exited on signal 11

### ISSUE THREAD

**Issue by zhengmz** [xxtea/xxtea-lua#2]
首先感谢开源xxtea-lua

我在openresty中使用xxtea.decrypt时，会出现“worker process 63 exited on signal 11”

openresty的版本是： 1.13.6.1

运行环境在 Docker中，使用的镜像是 openresty/openresty:alpine

我安装xxtea.so，是使用luarocks install xxtea

再次感谢

**Comment by andot** [comment]
上次修改之后，忘了发布了，现在更新了，你再试试看。

**Comment by zhengmz** [comment]
OK，可以了，谢谢。

**Comment by andot** [comment]
不客气。
